// Generated by CoffeeScript 1.9.3
(function() {
  var cmds, nomnom, readline, rl;

  nomnom = require('nomnom-alive');

  readline = require('readline');

  rl = readline.createInterface(process.stdin, process.stdout);

  rl.setPrompt('> ');

  rl.prompt();

  cmds = {};

  module.exports.on = function(cmd) {
    var c, parser;
    cmds[cmd] = {
      parser: parser = nomnom()
    };
    c = cmds[cmd];
    c.p = c.parser;
    c.p.printer(function(str, code) {
      return console.log(str);
    });
    c.p = c.p.command.apply(parser, arguments);
    return {
      opt: function() {
        c.p = c.p.option.apply(parser, arguments);
        return this;
      },
      opts: function() {
        c.p = c.p.options.apply(parser, arguments);
        return this;
      },
      cb: function(cb) {
        c.p = c.p.callback(function(opts) {
          opts._.shift();
          return cb.apply(this, arguments);
        });
        return this;
      }
    };
  };

  rl.on('line', function(line) {
    var cmd, parser;
    line = line.trim();
    if (line === '') {
      return rl.prompt();
    }
    for (cmd in cmds) {
      parser = cmds[cmd];
      if (0 !== line.search(cmd)) {
        continue;
      }
      try {
        parser.parser.parse(line.split(' '));
      } catch (_error) {}
      rl.prompt();
      return;
    }
    console.log("dont know " + line);
    return rl.prompt();
  });

}).call(this);
